template = "https://github.com/giellalt/template-lang-und"
rev_id = 260
template_sha = "2e95e152f66f76c7c7a22b2f9d91adbb75b07d95"

[replacements]
__GLOTTOLOG_ID__ = "paam1238"
__LICENSE__ = "LGPL-3.0"
__REPO__ = "lang-pma"
__UND2C__ = ""
__UNDEFINED__ = "Paamese"
__UND__ = "pma"
