template = "https://github.com/giellalt/template-lang-und"
rev_id = 268
template_sha = "444a55f5c0c0489e8f1dcde2639b74c44c24dffb"

[replacements]
__GLOTTOLOG_ID__ = "paam1238"
__LICENSE__ = "LGPL-3.0"
__REPO__ = "lang-pma"
__UND2C__ = ""
__UNDEFINED__ = "Paamese"
__UND__ = "pma"
